/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.37.1
  Forc version: 0.35.5
  Fuel-Core version: 0.17.3
*/

import type {
  BigNumberish,
  BN,
  BytesLike,
  Contract,
  DecodedValue,
  FunctionFragment,
  Interface,
  InvokeFunction,
} from 'fuels';

import type { Enum } from "./common";

export type AssetErrorInput = Enum<{ InvalidAssetId: [] }>;
export type AssetErrorOutput = AssetErrorInput;
export type IdentityInput = Enum<{ Address: AddressInput, ContractId: ContractIdInput }>;
export type IdentityOutput = Enum<{ Address: AddressOutput, ContractId: ContractIdOutput }>;
export type InputErrorInput = Enum<{ ExpectedNonZeroAddress: [], ExpectedNonZeroAmount: [] }>;
export type InputErrorOutput = InputErrorInput;
export type ProfileErrorInput = Enum<{ NonExistantProfile: [], InvalidProfileType: [] }>;
export type ProfileErrorOutput = ProfileErrorInput;
export type ProfileTypeInput = Enum<{ Startup: [], Investor: [] }>;
export type ProfileTypeOutput = ProfileTypeInput;
export type RegistrationValidityErrorInput = Enum<{ ExistantProfile: [] }>;
export type RegistrationValidityErrorOutput = RegistrationValidityErrorInput;

export type AddressInput = { value: string };
export type AddressOutput = AddressInput;
export type ContractIdInput = { value: string };
export type ContractIdOutput = ContractIdInput;
export type ProfileInfoInput = { name: string, description: string, url: string, profileType: ProfileTypeInput };
export type ProfileInfoOutput = { name: string, description: string, url: string, profileType: ProfileTypeOutput };

interface FuelMeAbiInterface extends Interface {
  functions: {
    get_profile: FunctionFragment;
    is_registered: FunctionFragment;
    register_profile: FunctionFragment;
    send_funds: FunctionFragment;
  };

  encodeFunctionData(functionFragment: 'get_profile', values: [IdentityInput]): Uint8Array;
  encodeFunctionData(functionFragment: 'is_registered', values: [IdentityInput]): Uint8Array;
  encodeFunctionData(functionFragment: 'register_profile', values: [string, string, string, BigNumberish]): Uint8Array;
  encodeFunctionData(functionFragment: 'send_funds', values: [IdentityInput]): Uint8Array;

  decodeFunctionData(functionFragment: 'get_profile', data: BytesLike): DecodedValue;
  decodeFunctionData(functionFragment: 'is_registered', data: BytesLike): DecodedValue;
  decodeFunctionData(functionFragment: 'register_profile', data: BytesLike): DecodedValue;
  decodeFunctionData(functionFragment: 'send_funds', data: BytesLike): DecodedValue;
}

export class FuelMeAbi extends Contract {
  interface: FuelMeAbiInterface;
  functions: {
    get_profile: InvokeFunction<[_startup: IdentityInput], ProfileInfoOutput>;
    is_registered: InvokeFunction<[_startup: IdentityInput], boolean>;
    register_profile: InvokeFunction<[_name: string, _description: string, _profileUrl: string, _profileType: BigNumberish], void>;
    send_funds: InvokeFunction<[_startup: IdentityInput], void>;
  };
}
