/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.37.1
  Forc version: 0.35.5
  Fuel-Core version: 0.17.3
*/

export type { FuelMeAbi } from './FuelMeAbi';

export { FuelMeAbi__factory } from './factories/FuelMeAbi__factory';
